AllCops:
  Exclude:
    - Rakefile
    - test/integration/**/*

Encoding:
  Enabled: false

LineLength:
  Max: 128

NumericLiterals:
  Enabled: false

MethodLength:
  Max: 40

GuardClause:
  Exclude:
    - providers/default.rb 
